# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# (실습준비) 데이터 불러오기부터

* 17년도부터 21년도 까지의 데이터를 train set, 22년도의 6개월치 데이터를 test set 으로 설정합니다.

In [684]:
import pandas as pd

# 학습 데이터 로딩
df_total = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/df_total.csv')
df_test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test/test2021.csv",sep=',',index_col=0)

In [303]:
#df_test=df_test[df_test['기준일ID']<'2022-03-01']

In [622]:
df_test.shape

(8760, 31)

---

In [73]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. 데이터 전처리

#### [실습문제1] 열 추가 
* 기존 '기준일ID'열에서 날짜 데이터를 추출하여 새로운 열로 추가 합니다.
    - pd.to_datetime() 함수를 사용해 '기준일ID'열을 datetime 형식으로 변경하겠습니다.
    - year, month, day 열로 기존 데이터 프레임에 연월일 정보를 저장합니다.
    - 데이터 프레임 열에 대해 날짜 정보를 얻을 때에는 **dt.year**, **dt.month**, **dt.day** 속성을 사용합니다.

In [685]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total['기준일ID']=pd.to_datetime(df_total['기준일ID'].astype('str'))

In [624]:
df_total.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,2017-01-01,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,1157.6661,1107.6781,1282.9235,1029.4360,998.0414,874.5643,1162.1547,1053.0477,964.3940,2025.4819
1,2017-01-01,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,...,1120.0051,1102.5198,1271.8997,1027.2574,1038.7528,857.9100,1149.7532,1042.7411,919.0115,2062.2422
2,2017-01-01,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,...,1103.1547,1112.4579,1282.9366,1027.8901,1020.0177,853.3890,1193.4472,1011.2073,889.9325,1960.1236
3,2017-01-01,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,...,1116.2165,1102.0668,1260.8472,1007.6650,1042.9554,896.0038,1163.0355,1056.6428,891.9177,2060.1872
4,2017-01-01,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,...,1187.5457,1120.2232,1281.2738,1064.0655,1045.2130,895.8336,1191.7017,1045.3362,874.4984,2038.6212

In [625]:
from datetime import date
df_total["년"] = [d.year for d in df_total["기준일ID"]]
df_total["월"] = [d.month for d in df_total["기준일ID"]]
df_total["일"] = [d.day for d in df_total["기준일ID"]]

In [686]:
df_test['기준일ID']=pd.to_datetime(df_test['기준일ID'].astype('str'))
df_test["년"] = [d.year for d in df_test["기준일ID"]]
df_test["월"] = [d.month for d in df_test["기준일ID"]]
df_test["일"] = [d.day for d in df_test["기준일ID"]]

In [429]:
df_test.tail()

,기준일ID,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일
4339,2022-06-30,19,32969.6040,2108.4754,613.9301,565.6419,904.1955,1338.8420,1416.2874,1785.9297,...,1315.6209,1221.7289,952.5630,1094.5123,932.6297,694.0737,1687.9623,2022,6,30
4340,2022-06-30,20,31014.6597,2017.9104,587.5599,542.7330,826.7983,1210.9392,1313.6926,1596.4043,...,1255.8520,1134.0779,906.4051,1016.0333,829.0177,693.8136,1679.0869,2022,6,30
4341,2022-06-30,21,30923.2923,2083.7634,606.7347,544.7149,813.5115,1175.5524,1279.7073,1659.6803,...,1236.1779,1113.2840,907.1416,1002.7494,835.7204,682.2879,1672.6951,2022,6,30
4342,2022-06-30,22,30509.5463,2186.0950,636.5307,573.6676,755.8347,1156.8269,1230.5487,1605.8491,...,1221.4595,1160.3239,879.1828,949.2953,821.7916,666.9312,1666.6319,2022,6,30
4343,2022-06-30,23,31184.8763,2179.2547,634.5390,580.9860,711.6332,1212.8320,1308.7377,1703.1838,...,1308.9829,1200.4453,840.6338,1001.2561,851.5886,716.4634,1761.5731,2022,6,30

#### [실습문제2] 불필요한 열 제거 및 열 이름 변경
* df_total과 df_test에서 '총생활인구수'외에 불필요한 열을 제거 하도록 하겠습니다.
* 시간 데이터를 남기고, '시간대구분' column 을 'hour'로 rename 하도록 하겠습니다.

In [687]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total.rename(columns={'시간대구분':'hour'},inplace=True)
df_test.rename(columns={'시간대구분':'hour'},inplace=True)

#### [실습문제3] 시프트 & 롤링
* shift()를 활용하여 이동할 행 수를 지정합니다.
* rolling()을 활용하여 추가할 이동평균 수를 지정합니다.

In [628]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# 1416 -> 이전 데이터로 1416시간 치의 예측치를 보겠다
#df_total['2m'] = df_total['총생활인구수'].shift(72)
df_total['1m'] = df_total['총생활인구수'].shift(48)
df_total['1d'] = df_total['총생활인구수'].shift(24)
df_total['1h'] = df_total['총생활인구수'].shift(1)
#df_total['2d_y'] = df_total['총생활인구수'].shift(24*7)

In [688]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_test['2m'] = df_test['총생활인구수'].shift(1416)
df_test['1m'] = df_test['총생활인구수'].shift(48)
df_test['1d'] = df_test['총생활인구수'].shift(24)
df_test['1h'] = df_test['총생활인구수'].shift(1)

In [630]:
df_total['2m_mean']=df_total['총생활인구수'].rolling(window=1416).mean()
df_test['2m_mean']=df_test['총생활인구수'].rolling(window=1416).mean()

In [689]:
df_test[:1416]

,기준일ID,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일,2m,1m,1d,1h
0,2021-01-01,0,38538.5993,785.1305,516.8260,816.9894,1572.9164,2240.8970,1632.0217,1534.7635,...,1176.5204,925.9878,2614.2247,2021,1,1,NaN,NaN,NaN,NaN
1,2021-01-01,1,38457.1528,824.8142,542.9229,796.3712,1564.3204,2257.5202,1634.1890,1506.8692,...,1185.5568,907.0416,2607.8748,2021,1,1,NaN,NaN,NaN,38538.5993
2,2021-01-01,2,38185.1451,843.5537,555.2454,795.1706,1571.2800,2249.8246,1626.4571,1490.7254,...,1164.7066,905.4539,2586.4604,2021,1,1,NaN,NaN,NaN,38457.1528
3,2021-01-01,3,38074.2836,830.9181,546.9359,782.9169,1578.1156,2252.4146,1609.4993,1491.9290,...,1157.7801,909.6394,2577.8385,2021,1,1,NaN,NaN,NaN,38185.1451
4,2021-01-01,4,38229.0027,842.3246,554.4371,778.0671,1574.4996,2223.7735,1615.1989,1504.2698,...,1167.3582,911.4016,2615.9563,2021,1,1,NaN,NaN,NaN,38074.2836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1411,2021-02-28,19,36466.6586,831.8679,547.5610,678.8401,1450.3208,2032.0794,1532.9602,1457.6956,...,1068.0789,837.9507,2413.5149,2021,2,28,NaN,36661.0530,36272.4528,36330.3196
1412,2021-02-28,20,36795.4254,753.8968,496.2862,742.5854,1520.8199,2075.0495,1543.8182,1431.8297,...,1076.2694,851.5807,2413.2240,2021,2,28,NaN,36800.4719,35946.3156,36466.6586
1413,2021-02-28,21,37333.9824,830.9553,546.9610,762.8522,1595.8114,2135.2242,1510.2869,1476.3965,...,1025.3734,853.6905,2497.3728,2021,2,28,NaN,37111.8435,36496.0305,36795.4254
1414,2021-02-28,22,37630.8536,831.4981,547.3179,777.1579,1689.2368,2196.1344,1540.0866,1495.3230,...,1032.9598,855.8833,2424.4101,2021,2,28,NaN,38134.3374,37018.6773,37333.9824
1415,2021-02-28,23,40114.2226,789.8470,519.9274,873.8070,1864.4786,2449.1178,1654.1729,1609.3519,...,1144.2713,930.0568,2670.7113,2021,2,28,NaN,40884.1169,39399.2520,37630.8536

#### [실습문제4] 결측치 처리 및 불필요한 열 제거
* 롤링 & 시프트 과정에서 발생한 결측치를 처리하도록 하겠습니다.
* 불필요한 열을 추가로 제거 하겠습니다.(시간 관련 행들)

In [444]:
from sklearn.impute import KNNImputer

In [661]:
imputer=KNNImputer(n_neighbors=1416)

In [662]:
df_total[['1m','1d','1h']]=imputer.fit_transform(df_total[['1m','1d','1h']])
df_test[['1m','1d','1h']]=imputer.fit_transform(df_test[['1m','1d','1h']])

KeyError: ignored

In [593]:
df_total

,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,...,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일,1m,1d,1h
0,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,1236.7535,...,1162.1547,1053.0477,964.3940,2025.4819,2017,1,1,37392.990711,37391.883052,37390.823426
1,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,1236.8635,...,1149.7532,1042.7411,919.0115,2062.2422,2017,1,1,32164.783850,32063.348546,31535.220000
2,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,1211.8326,...,1193.4472,1011.2073,889.9325,1960.1236,2017,1,1,31871.547256,31709.431329,31188.917400
3,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,1232.8897,...,1163.0355,1056.6428,891.9177,2060.1872,2017,1,1,31876.959479,31799.867325,31240.497400
4,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,1282.1621,...,1191.7017,1045.3362,874.4984,2038.6212,2017,1,1,32086.046758,31883.631777,31442.431400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43507,19,33060.4555,1858.2611,541.0746,605.9080,781.6602,1342.6763,1435.1080,1678.8904,1605.1525,...,1091.7204,942.1525,789.2094,1705.8216,2021,12,31,33598.005600,33928.205100,35883.187400
43508,20,32360.1898,2093.8808,609.6807,612.5326,768.8351,1323.7124,1479.1382,1654.5005,1533.4662,...,1062.8069,894.8617,792.1748,1726.3071,2021,12,31,33062.637400,33712.534800,33060.455500
43509,21,31417.3991,1983.6728,577.5909,639.2174,779.6693,1187.6783,1375.6785,1600.9946,1423.7113,...,999.7321,874.9000,770.3955,1674.6047,2021,12,31,32348.175500,32144.491700,32360.189800
43510,22,30763.0563,2028.3314,590.5941,654.0295,790.1638,1133.6311,1362.0266,1548.7366,1456.9716,...,991.0451,848.4622,753.9750,1727.0258,2021,12,31,31577.931100,32137.701700,31417.399100
43511,23,30404.2740,1903.8825,554.3582,615.0753,772.8499,1136.6157,1295.0434,1549.1984,1508.8052,...,986.6660,872.1547,734.2503,1759.0664,2021,12,31,31878.486900,31641.169800,30763.056300

In [455]:
z=pd.DataFrame(z)

In [456]:
z

                 0             1             2
0     36007.123902  36005.031609  36014.391468
1     31357.415333  30509.738600  31696.491238
2     31759.515993  30759.506700  32025.654867
3     31684.389207  31048.878700  31919.715529
4     31647.024262  31076.109200  31900.883636
...            ...           ...           ...
4339  31689.821200  34644.224600  32907.946100
4340  30425.905400  32969.604000  30277.025500
4341  30352.886900  31014.659700  30607.292200
4342  30232.284600  30923.292300  30683.557100
4343  31251.411900  30509.546300  31215.131700

[4344 rows x 3 columns]

In [443]:
# # 아래에 실습코드를 작성하고 결과를 확인합니다.
# # df_total.dropna(axis=0,inplace=True)
# # df_test.dropna(axis=0,inplace=True)
# #df_total.fillna(df_total.mean(),inplace=True)
# #df_test.fillna(df_test.mean(),inplace=True)
# df_test['1m'].interpolate(limit_direction='backward')

0       30509.7386
1       30509.7386
2       30509.7386
3       30509.7386
4       30509.7386
           ...
4339    32907.9461
4340    30277.0255
4341    30607.2922
4342    30683.5571
4343    31215.1317
Name: 1m, Length: 4344, dtype: float64

In [633]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total.drop(labels='기준일ID',axis=1,inplace=True)
df_test.drop(labels='기준일ID',axis=1,inplace=True)

In [ ]:
# df_total.drop(labels='총생활인구수',axis=1,inplace=True)
# df_test.drop(labels='총생활인구수',axis=1,inplace=True)

In [527]:
df_total.shape

(43512, 37)

In [528]:
df_test.shape

(4344, 37)

In [529]:
test=pd.concat([df_total,df_test])

In [530]:
test

,기준일ID,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일,1m,1d,1h
0,2017-01-01,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,1162.1547,1053.0477,964.3940,2025.4819,2017,1,1,37392.990711,37391.883052,37390.823426
1,2017-01-01,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,...,1149.7532,1042.7411,919.0115,2062.2422,2017,1,1,32164.783850,32063.348546,31535.220000
2,2017-01-01,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,...,1193.4472,1011.2073,889.9325,1960.1236,2017,1,1,31871.547256,31709.431329,31188.917400
3,2017-01-01,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,...,1163.0355,1056.6428,891.9177,2060.1872,2017,1,1,31876.959479,31799.867325,31240.497400
4,2017-01-01,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,...,1191.7017,1045.3362,874.4984,2038.6212,2017,1,1,32086.046758,31883.631777,31442.431400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4339,2022-06-30,19,32969.6040,2108.4754,613.9301,565.6419,904.1955,1338.8420,1416.2874,1785.9297,...,1094.5123,932.6297,694.0737,1687.9623,2022,6,30,32907.946100,31689.821200,34644.224600
4340,2022-06-30,20,31014.6597,2017.9104,587.5599,542.7330,826.7983,1210.9392,1313.6926,1596.4043,...,1016.0333,829.0177,693.8136,1679.0869,2022,6,30,30277.025500,30425.905400,32969.604000
4341,2022-06-30,21,30923.2923,2083.7634,606.7347,544.7149,813.5115,1175.5524,1279.7073,1659.6803,...,1002.7494,835.7204,682.2879,1672.6951,2022,6,30,30607.292200,30352.886900,31014.659700
4342,2022-06-30,22,30509.5463,2186.0950,636.5307,573.6676,755.8347,1156.8269,1230.5487,1605.8491,...,949.2953,821.7916,666.9312,1666.6319,2022,6,30,30683.557100,30232.284600,30923.292300
4343,2022-06-30,23,31184.8763,2179.2547,634.5390,580.9860,711.6332,1212.8320,1308.7377,1703.1838,...,1001.2561,851.5886,716.4634,1761.5731,2022,6,30,31215.131700,31251.411900,30509.546300

#### [실습문제5] train, test 데이터 나누기
* df_total과 df_test를 각각 train_x, train_y, test_x, test_y 로 나누어 주세요.
* 인덱스를 리셋 해주세요.

In [634]:
df=pd.concat([kaggle_total,df_test])

In [635]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43512 entries, 0 to 8759
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   hour             43512 non-null  int64
 1   총생활인구수           43512 non-null  float64
 2   남자0세부터9세생활인구수    43512 non-null  float64
 3   남자10세부터14세생활인구수  43512 non-null  float64
 4   남자15세부터19세생활인구수  43512 non-null  float64
 5   남자20세부터24세생활인구수  43512 non-null  float64
 6   남자25세부터29세생활인구수  43512 non-null  float64
 7   남자30세부터34세생활인구수  43512 non-null  float64
 8   남자35세부터39세생활인구수  43512 non-null  float64
 9   남자40세부터44세생활인구수  43512 non-null  float64
 10  남자45세부터49세생활인구수  43512 non-null  float64
 11  남자50세부터54세생활인구수  43512 non-null  float64
 12  남자55세부터59세생활인구수  43512 non-null  float64
 13  남자60세부터64세생활인구수  43512 non-null  float64
 14  남자65세부터69세생활인구수  43512 non-null  float64
 15  남자70세이상생활인구수     43512 non-null  float64
 16  여자0세부터9세생활인구수    43512 non-null  float64
 17  여자10세부터14세생활인구수  43512 non-null  float64
 18  여자15세부터19세생활인구수  43512 non-null  float64
 19  여자20세부터24세생활인구수  43512 non-null  float64
 20  여자25세부터29세생활인구수  43512 non-null  float64
 21  여자30세부터34세생활인구수  43512 non-null  float64
 22  여자35세부터39세생활인구수  43512 non-null  float64
 23  여자40세부터44세생활인구수  43512 non-null  float64
 24  여자45세부터49세생활인구수  43512 non-null  float64
 25  여자50세부터54세생활인구수  43512 non-null  float64
 26  여자55세부터59세생활인구수  43512 non-null  float64
 27  여자60세부터64세생활인구수  43512 non-null  float64
 28  여자65세부터69세생활인구수  43512 non-null  float64
 29  여자70세이상생활인구수     43512 non-null  float64
 30  년                43512 non-null  int64
 31  월                43512 non-null  int64
 32  일                43512 non-null  int64
 33  1m               43512 non-null  float64
 34  1d               43512 non-null  float64
 35  1h               43512 non-null  float64
 36  2m_mean          40682 non-null  float64
dtypes: float64(33), int64(4)
memory usage: 12.6 MB

In [450]:
z=df_test[['1d','1h','1m']]

In [299]:
#z=z.iloc[-1416:]

In [457]:
z.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/z.csv', index = False)

In [413]:
z

,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,남자45세부터49세생활인구수,남자50세부터54세생활인구수,...,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,2m,1m,1d,1h,2m_mean
0,1884.2082,548.6298,635.1617,816.1686,1140.0136,1310.3109,1528.2100,1490.5116,1404.8348,1065.0661,...,823.9020,1032.1651,872.8850,767.0226,1737.1551,36022.332265,36014.391468,36007.123902,36005.031609,35861.341868
1,1918.5330,558.6242,665.6793,822.6910,1159.5614,1293.1350,1542.7586,1485.2323,1410.6036,1091.6283,...,838.5323,998.1091,862.3041,776.7908,1753.0597,36022.332265,36014.391468,36007.123902,30509.738600,35861.341868
2,2068.1943,602.2013,680.8294,819.7141,1164.5819,1331.9311,1537.8207,1493.3085,1417.3893,1071.1076,...,840.6799,1026.5402,882.2846,772.8478,1757.8801,36022.332265,36014.391468,36007.123902,30759.506700,35861.341868
3,1951.7702,568.3016,690.9847,804.2219,1180.7028,1336.8848,1542.4681,1474.2258,1451.9811,1074.2364,...,856.1711,1042.1205,891.6092,785.1560,1747.8953,36022.332265,36014.391468,36007.123902,31048.878700,35861.341868
4,2058.5797,599.4019,708.3313,847.9704,1168.0681,1355.7735,1586.0121,1506.2284,1468.1769,1117.7423,...,875.1503,1052.5656,877.6836,795.0789,1760.4713,36022.332265,36014.391468,36007.123902,31076.109200,35861.341868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4339,2108.4754,613.9301,565.6419,904.1955,1338.8420,1416.2874,1785.9297,1629.3457,1694.5841,1228.3755,...,952.5630,1094.5123,932.6297,694.0737,1687.9623,32629.944400,32907.946100,31689.821200,34644.224600,37846.469234
4340,2017.9104,587.5599,542.7330,826.7983,1210.9392,1313.6926,1596.4043,1560.6974,1480.1491,1096.2014,...,906.4051,1016.0333,829.0177,693.8136,1679.0869,30755.298700,30277.025500,30425.905400,32969.604000,37845.015671
4341,2083.7634,606.7347,544.7149,813.5115,1175.5524,1279.7073,1659.6803,1472.3995,1529.2493,1092.0332,...,907.1416,1002.7494,835.7204,682.2879,1672.6951,31093.672100,30607.292200,30352.886900,31014.659700,37843.673967
4342,2186.0950,636.5307,573.6676,755.8347,1156.8269,1230.5487,1605.8491,1453.4369,1492.6830,1081.6068,...,879.1828,949.2953,821.7916,666.9312,1666.6319,30694.525100,30683.557100,30232.284600,30923.292300,37842.429963
4343,2179.2547,634.5390,580.9860,711.6332,1212.8320,1308.7377,1703.1838,1547.4281,1483.2965,1051.7263,...,840.6338,1001.2561,851.5886,716.4634,1761.5731,30756.097200,31215.131700,31251.411900,30509.546300,37841.185041

In [802]:
kaggle_total

,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,...,여자70세이상생활인구수,년,월,일,2m,2m1d,2m7d,1m,1d,1h
1584,0,45455.3554,954.5095,628.2123,1238.6387,3303.3939,3096.6219,1865.0555,1653.2787,1504.1821,...,3252.0174,2017,3,8,45343.5803,45473.5373,43922.2281,45599.5255,45109.1336,45026.9279
1585,1,45680.9697,937.1151,616.7727,1269.3236,3406.3023,3200.1702,1858.1405,1684.7867,1484.8518,...,3251.7928,2017,3,8,45360.8773,45881.6978,43763.4929,45616.7501,45613.2005,45455.3554
1586,2,45637.7142,926.1780,609.5810,1262.9127,3426.0155,3173.1311,1862.8322,1677.1918,1481.0387,...,3255.3011,2017,3,8,45406.4553,46043.4090,43561.5708,45722.2274,44703.8624,45680.9697
1587,3,46583.8557,960.2701,631.9998,1276.2711,3486.0706,3235.5200,1918.4199,1703.5888,1535.3799,...,3299.1237,2017,3,8,45714.8724,46196.8840,43928.9929,45778.9722,44830.0410,45637.7142
1588,4,46892.5482,964.2275,634.6029,1293.4217,3492.8881,3277.0146,1907.3554,1676.3739,1523.4703,...,3291.0160,2017,3,8,45893.9595,46486.5784,44150.2973,45888.3440,45186.2041,46583.8557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,19,33304.5400,569.3452,374.9229,702.9942,1195.0912,1818.2627,1434.7351,1439.8129,1324.4270,...,2239.1210,2021,12,31,35708.4819,36087.9937,35815.6482,34478.8443,34687.7515,33773.1695
8756,20,33368.7201,599.9827,395.0698,806.5718,1232.5401,1781.4567,1441.6411,1469.7313,1293.6881,...,2226.3545,2021,12,31,35924.7026,36339.3987,36009.3918,35128.7653,34728.1718,33304.5400
8757,21,34083.1721,630.5049,415.1424,825.4794,1360.3197,1866.0852,1428.3237,1490.6164,1336.9576,...,2249.0323,2021,12,31,36597.7205,36527.5722,36339.1032,35839.3935,35767.8222,33368.7201
8758,22,34380.0806,618.6265,407.3311,831.6651,1364.7723,1899.4216,1416.2191,1473.4710,1309.9313,...,2263.6665,2021,12,31,37163.4665,36940.6312,37097.1192,36116.1812,36193.0573,34083.1721
8759,23,37074.2785,734.2128,483.3418,895.2420,1594.0355,2116.7695,1519.3632,1552.7195,1419.5751,...,2520.7282,2021,12,31,39853.9949,40458.3040,40566.3709,38996.5994,38468.1344,34380.0806

In [843]:
#x=kaggle_total.drop(['년','월','일','hour'],axis=1)
x=kaggle_total[['1d','1h','1m','총생활인구수','2m1d','2m7d']]
y=kaggle_total.loc[:,'2m']

In [831]:
y

1584    45343.5803
1585    45360.8773
1586    45406.4553
1587    45714.8724
1588    45893.9595
           ...
8755    35708.4819
8756    35924.7026
8757    36597.7205
8758    37163.4665
8759    39853.9949
Name: 2m, Length: 41928, dtype: float64

In [844]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 1416, shuffle = False) #30 : 자연수 - 개수, shuffle : 섞어라

In [845]:
df_test.shape

(8760, 38)

In [846]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_x.shape,test_x.shape

((40512, 6), (1416, 6))

In [847]:
test_x

              1d          1h          1m      총생활인구수        2m1d        2m7d
7344  39865.1548  39853.9949  41075.7126  39873.2794  40844.0424  39557.0898
7345  39818.4645  39873.2794  40723.4197  39797.9224  40635.2950  39223.3456
7346  39863.9256  39797.9224  40734.4965  39671.0867  40439.3407  38944.0069
7347  39629.7011  39671.0867  40701.1690  39720.9665  40338.1786  38902.0554
7348  39955.2211  39720.9665  40678.9959  39897.9873  40312.9573  38837.8244
...          ...         ...         ...         ...         ...         ...
8755  34687.7515  33773.1695  34478.8443  33304.5400  36087.9937  35815.6482
8756  34728.1718  33304.5400  35128.7653  33368.7201  36339.3987  36009.3918
8757  35767.8222  33368.7201  35839.3935  34083.1721  36527.5722  36339.1032
8758  36193.0573  34083.1721  36116.1812  34380.0806  36940.6312  37097.1192
8759  38468.1344  34380.0806  38996.5994  37074.2785  40458.3040  40566.3709

[1416 rows x 6 columns]

---

## 다음 단계를 위해서 데이터를 저장하겠습니다.

In [848]:
# CSV로 저장
train_x.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/train_x.csv', index = False)
train_y.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/train_y.csv', index = False)
test_x.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test_x.csv', index = False)
test_y.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test_y.csv', index = False)

In [386]:
df_test

,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,...,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일,2m,1m,1d,1h,2m_mean
0,0,30509.7386,1884.2082,548.6298,635.1617,816.1686,1140.0136,1310.3109,1528.2100,1490.5116,...,767.0226,1737.1551,2022,1,1,36022.332265,36014.391468,36007.123902,36005.031609,35861.341868
1,1,30759.5067,1918.5330,558.6242,665.6793,822.6910,1159.5614,1293.1350,1542.7586,1485.2323,...,776.7908,1753.0597,2022,1,1,36022.332265,36014.391468,36007.123902,30509.738600,35861.341868
2,2,31048.8787,2068.1943,602.2013,680.8294,819.7141,1164.5819,1331.9311,1537.8207,1493.3085,...,772.8478,1757.8801,2022,1,1,36022.332265,36014.391468,36007.123902,30759.506700,35861.341868
3,3,31076.1092,1951.7702,568.3016,690.9847,804.2219,1180.7028,1336.8848,1542.4681,1474.2258,...,785.1560,1747.8953,2022,1,1,36022.332265,36014.391468,36007.123902,31048.878700,35861.341868
4,4,31714.9309,2058.5797,599.4019,708.3313,847.9704,1168.0681,1355.7735,1586.0121,1506.2284,...,795.0789,1760.4713,2022,1,1,36022.332265,36014.391468,36007.123902,31076.109200,35861.341868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4339,19,32969.6040,2108.4754,613.9301,565.6419,904.1955,1338.8420,1416.2874,1785.9297,1629.3457,...,694.0737,1687.9623,2022,6,30,32629.944400,32907.946100,31689.821200,34644.224600,37846.469234
4340,20,31014.6597,2017.9104,587.5599,542.7330,826.7983,1210.9392,1313.6926,1596.4043,1560.6974,...,693.8136,1679.0869,2022,6,30,30755.298700,30277.025500,30425.905400,32969.604000,37845.015671
4341,21,30923.2923,2083.7634,606.7347,544.7149,813.5115,1175.5524,1279.7073,1659.6803,1472.3995,...,682.2879,1672.6951,2022,6,30,31093.672100,30607.292200,30352.886900,31014.659700,37843.673967
4342,22,30509.5463,2186.0950,636.5307,573.6676,755.8347,1156.8269,1230.5487,1605.8491,1453.4369,...,666.9312,1666.6319,2022,6,30,30694.525100,30683.557100,30232.284600,30923.292300,37842.429963
4343,23,31184.8763,2179.2547,634.5390,580.9860,711.6332,1212.8320,1308.7377,1703.1838,1547.4281,...,716.4634,1761.5731,2022,6,30,30756.097200,31215.131700,31251.411900,30509.546300,37841.185041

## kaggle

In [780]:
kaggle_17=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test/test2017.csv",sep=',',index_col=0)
kaggle_18=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test/test2018.csv",sep=',',index_col=0)
kaggle_19=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test/test2019.csv",sep=',',index_col=0)
kaggle_20=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test/test2020.csv",sep=',',index_col=0)
kaggle_21=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test/test2021.csv",sep=',',index_col=0)

In [781]:
kaggle_17.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20170101,0,43922.2281,953.7652,627.7225,927.6134,2025.0630,2278.7336,1744.8161,1713.6754,...,2060.1511,1734.3805,1713.3332,1754.6515,1636.4175,1521.3668,1728.0639,1484.4518,1238.2606,3670.0451
1,20170101,1,43763.4929,962.2909,633.3292,970.6215,2045.7002,2412.6287,1765.7725,1765.1171,...,2037.5677,1745.5960,1735.4797,1700.9196,1619.3672,1474.8418,1661.3750,1470.3009,1098.4788,3568.8258
2,20170101,2,43561.5708,932.2939,613.6027,964.3505,2057.3601,2419.0941,1734.0569,1746.3940,...,2005.4838,1750.7594,1710.6116,1660.6697,1660.9852,1511.4103,1635.0352,1441.0173,1112.3632,3541.2620
3,20170101,3,43928.9929,926.3617,609.7009,983.2400,2100.5071,2480.1898,1780.3833,1723.6640,...,2044.6913,1777.4169,1718.1475,1678.9374,1626.8350,1516.5837,1665.8781,1471.2127,1098.3154,3630.0822
4,20170101,4,44150.2973,922.8893,607.4184,990.0534,2128.2729,2531.6549,1774.7853,1752.0073,...,2060.8824,1801.2144,1718.2957,1678.6174,1640.9056,1513.5035,1653.2704,1435.5180,1090.4059,3569.1653

In [782]:
kaggle_total=pd.concat([kaggle_17,kaggle_18,kaggle_19,kaggle_20,kaggle_21])

In [783]:
kaggle_total.shape

(43512, 31)

In [784]:
kaggle_total.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20170101,0,43922.2281,953.7652,627.7225,927.6134,2025.0630,2278.7336,1744.8161,1713.6754,...,2060.1511,1734.3805,1713.3332,1754.6515,1636.4175,1521.3668,1728.0639,1484.4518,1238.2606,3670.0451
1,20170101,1,43763.4929,962.2909,633.3292,970.6215,2045.7002,2412.6287,1765.7725,1765.1171,...,2037.5677,1745.5960,1735.4797,1700.9196,1619.3672,1474.8418,1661.3750,1470.3009,1098.4788,3568.8258
2,20170101,2,43561.5708,932.2939,613.6027,964.3505,2057.3601,2419.0941,1734.0569,1746.3940,...,2005.4838,1750.7594,1710.6116,1660.6697,1660.9852,1511.4103,1635.0352,1441.0173,1112.3632,3541.2620
3,20170101,3,43928.9929,926.3617,609.7009,983.2400,2100.5071,2480.1898,1780.3833,1723.6640,...,2044.6913,1777.4169,1718.1475,1678.9374,1626.8350,1516.5837,1665.8781,1471.2127,1098.3154,3630.0822
4,20170101,4,44150.2973,922.8893,607.4184,990.0534,2128.2729,2531.6549,1774.7853,1752.0073,...,2060.8824,1801.2144,1718.2957,1678.6174,1640.9056,1513.5035,1653.2704,1435.5180,1090.4059,3569.1653

In [785]:
kaggle_total['기준일ID']=pd.to_datetime(kaggle_total['기준일ID'].astype('str'))

In [786]:
from datetime import date
kaggle_total["년"] = [d.year for d in kaggle_total["기준일ID"]]
kaggle_total["월"] = [d.month for d in kaggle_total["기준일ID"]]
kaggle_total["일"] = [d.day for d in kaggle_total["기준일ID"]]

In [787]:
kaggle_total.rename(columns={'시간대구분':'hour'},inplace=True)

In [788]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# 1416 -> 이전 데이터로 1416시간 치의 예측치를 보겠다
kaggle_total['2m'] = kaggle_total['총생활인구수'].shift(1416)
kaggle_total['2m1d'] = kaggle_total['총생활인구수'].shift(1416+24)
kaggle_total['2m7d'] = kaggle_total['총생활인구수'].shift(1416+(24*7))
kaggle_total['1m'] = kaggle_total['총생활인구수'].shift(48)
kaggle_total['1d'] = kaggle_total['총생활인구수'].shift(24)
kaggle_total['1h'] = kaggle_total['총생활인구수'].shift(1)
#df_total['2d_y'] = df_total['총생활인구수'].shift(24*7)

In [789]:
kaggle_total

,기준일ID,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자70세이상생활인구수,년,월,일,2m,2m1d,2m7d,1m,1d,1h
0,2017-01-01,0,43922.2281,953.7652,627.7225,927.6134,2025.0630,2278.7336,1744.8161,1713.6754,...,3670.0451,2017,1,1,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-01-01,1,43763.4929,962.2909,633.3292,970.6215,2045.7002,2412.6287,1765.7725,1765.1171,...,3568.8258,2017,1,1,NaN,NaN,NaN,NaN,NaN,43922.2281
2,2017-01-01,2,43561.5708,932.2939,613.6027,964.3505,2057.3601,2419.0941,1734.0569,1746.3940,...,3541.2620,2017,1,1,NaN,NaN,NaN,NaN,NaN,43763.4929
3,2017-01-01,3,43928.9929,926.3617,609.7009,983.2400,2100.5071,2480.1898,1780.3833,1723.6640,...,3630.0822,2017,1,1,NaN,NaN,NaN,NaN,NaN,43561.5708
4,2017-01-01,4,44150.2973,922.8893,607.4184,990.0534,2128.2729,2531.6549,1774.7853,1752.0073,...,3569.1653,2017,1,1,NaN,NaN,NaN,NaN,NaN,43928.9929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2021-12-31,19,33304.5400,569.3452,374.9229,702.9942,1195.0912,1818.2627,1434.7351,1439.8129,...,2239.1210,2021,12,31,35708.4819,36087.9937,35815.6482,34478.8443,34687.7515,33773.1695
8756,2021-12-31,20,33368.7201,599.9827,395.0698,806.5718,1232.5401,1781.4567,1441.6411,1469.7313,...,2226.3545,2021,12,31,35924.7026,36339.3987,36009.3918,35128.7653,34728.1718,33304.5400
8757,2021-12-31,21,34083.1721,630.5049,415.1424,825.4794,1360.3197,1866.0852,1428.3237,1490.6164,...,2249.0323,2021,12,31,36597.7205,36527.5722,36339.1032,35839.3935,35767.8222,33368.7201
8758,2021-12-31,22,34380.0806,618.6265,407.3311,831.6651,1364.7723,1899.4216,1416.2191,1473.4710,...,2263.6665,2021,12,31,37163.4665,36940.6312,37097.1192,36116.1812,36193.0573,34083.1721
8759,2021-12-31,23,37074.2785,734.2128,483.3418,895.2420,1594.0355,2116.7695,1519.3632,1552.7195,...,2520.7282,2021,12,31,39853.9949,40458.3040,40566.3709,38996.5994,38468.1344,34380.0806

In [616]:
#kaggle_total['2m_mean']=kaggle_total['총생활인구수'].rolling(window=1416).mean()

In [396]:
#kaggle_total.fillna(kaggle_total.mean(),inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  """Entry point for launching an IPython kernel.

In [790]:
kaggle_total.dropna(inplace=True)

In [677]:
#kaggle_total[['2m''1m','1d','1h']]=imputer.fit_transform(kaggle_total[['2m','1m','1d','1h']])

ValueError: ignored

In [791]:
kaggle_total.drop(labels='기준일ID',axis=1,inplace=True)

In [792]:
kaggle_total.shape

(41928, 39)

In [793]:
kaggle_total[-1416:]

,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,...,여자70세이상생활인구수,년,월,일,2m,2m1d,2m7d,1m,1d,1h
7344,0,39873.2794,743.7121,489.5886,883.5690,1861.1021,2475.2152,1666.9890,1678.1501,1552.9658,...,2336.9589,2021,11,3,39344.5300,40844.0424,39557.0898,41075.7126,39865.1548,39853.9949
7345,1,39797.9224,742.0359,488.4867,896.8553,1876.3038,2499.8235,1657.4161,1640.2844,1529.6343,...,2352.0115,2021,11,3,39092.8105,40635.2950,39223.3456,40723.4197,39818.4645,39873.2794
7346,2,39671.0867,741.9842,488.4521,882.3180,1898.6497,2513.3687,1651.0475,1629.7286,1505.1602,...,2339.9466,2021,11,3,39044.0701,40439.3407,38944.0069,40734.4965,39863.9256,39797.9224
7347,3,39720.9665,736.3469,484.7453,882.8488,1916.0125,2526.8064,1676.6193,1649.9841,1489.7083,...,2326.0336,2021,11,3,38895.5915,40338.1786,38902.0554,40701.1690,39629.7011,39671.0867
7348,4,39897.9873,723.5644,476.3390,883.8463,1923.8676,2531.9090,1694.4750,1668.9616,1499.7933,...,2387.2073,2021,11,3,38884.0841,40312.9573,38837.8244,40678.9959,39955.2211,39720.9665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,19,33304.5400,569.3452,374.9229,702.9942,1195.0912,1818.2627,1434.7351,1439.8129,1324.4270,...,2239.1210,2021,12,31,35708.4819,36087.9937,35815.6482,34478.8443,34687.7515,33773.1695
8756,20,33368.7201,599.9827,395.0698,806.5718,1232.5401,1781.4567,1441.6411,1469.7313,1293.6881,...,2226.3545,2021,12,31,35924.7026,36339.3987,36009.3918,35128.7653,34728.1718,33304.5400
8757,21,34083.1721,630.5049,415.1424,825.4794,1360.3197,1866.0852,1428.3237,1490.6164,1336.9576,...,2249.0323,2021,12,31,36597.7205,36527.5722,36339.1032,35839.3935,35767.8222,33368.7201
8758,22,34380.0806,618.6265,407.3311,831.6651,1364.7723,1899.4216,1416.2191,1473.4710,1309.9313,...,2263.6665,2021,12,31,37163.4665,36940.6312,37097.1192,36116.1812,36193.0573,34083.1721
8759,23,37074.2785,734.2128,483.3418,895.2420,1594.0355,2116.7695,1519.3632,1552.7195,1419.5751,...,2520.7282,2021,12,31,39853.9949,40458.3040,40566.3709,38996.5994,38468.1344,34380.0806

In [794]:
kaggle_total.drop(['년','월','일'],axis=1)

,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,...,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,2m,2m1d,2m7d,1m,1d,1h
1584,0,45455.3554,954.5095,628.2123,1238.6387,3303.3939,3096.6219,1865.0555,1653.2787,1504.1821,...,1554.5362,1395.6278,1074.3024,3252.0174,45343.5803,45473.5373,43922.2281,45599.5255,45109.1336,45026.9279
1585,1,45680.9697,937.1151,616.7727,1269.3236,3406.3023,3200.1702,1858.1405,1684.7867,1484.8518,...,1537.7381,1384.8123,1052.0447,3251.7928,45360.8773,45881.6978,43763.4929,45616.7501,45613.2005,45455.3554
1586,2,45637.7142,926.1780,609.5810,1262.9127,3426.0155,3173.1311,1862.8322,1677.1918,1481.0387,...,1546.3995,1364.3985,1082.2362,3255.3011,45406.4553,46043.4090,43561.5708,45722.2274,44703.8624,45680.9697
1587,3,46583.8557,960.2701,631.9998,1276.2711,3486.0706,3235.5200,1918.4199,1703.5888,1535.3799,...,1606.9486,1383.5643,1116.3015,3299.1237,45714.8724,46196.8840,43928.9929,45778.9722,44830.0410,45637.7142
1588,4,46892.5482,964.2275,634.6029,1293.4217,3492.8881,3277.0146,1907.3554,1676.3739,1523.4703,...,1627.2366,1384.2572,1118.7991,3291.0160,45893.9595,46486.5784,44150.2973,45888.3440,45186.2041,46583.8557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,19,33304.5400,569.3452,374.9229,702.9942,1195.0912,1818.2627,1434.7351,1439.8129,1324.4270,...,1342.7762,1058.0542,749.3935,2239.1210,35708.4819,36087.9937,35815.6482,34478.8443,34687.7515,33773.1695
8756,20,33368.7201,599.9827,395.0698,806.5718,1232.5401,1781.4567,1441.6411,1469.7313,1293.6881,...,1336.5298,1056.6818,756.4905,2226.3545,35924.7026,36339.3987,36009.3918,35128.7653,34728.1718,33304.5400
8757,21,34083.1721,630.5049,415.1424,825.4794,1360.3197,1866.0852,1428.3237,1490.6164,1336.9576,...,1336.1856,1042.3110,750.1392,2249.0323,36597.7205,36527.5722,36339.1032,35839.3935,35767.8222,33368.7201
8758,22,34380.0806,618.6265,407.3311,831.6651,1364.7723,1899.4216,1416.2191,1473.4710,1309.9313,...,1334.5079,1045.8411,762.5466,2263.6665,37163.4665,36940.6312,37097.1192,36116.1812,36193.0573,34083.1721
8759,23,37074.2785,734.2128,483.3418,895.2420,1594.0355,2116.7695,1519.3632,1552.7195,1419.5751,...,1319.0559,1138.3249,816.1801,2520.7282,39853.9949,40458.3040,40566.3709,38996.5994,38468.1344,34380.0806