# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# (실습준비) 데이터 불러오기부터

* 17년도부터 21년도 까지의 데이터를 train set, 22년도의 6개월치 데이터를 test set 으로 설정합니다.

In [307]:
import pandas as pd

# 학습 데이터 로딩
df_total = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/df_total.csv')
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/df_test.csv')

---

In [213]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. 데이터 전처리

#### [실습문제1] 열 추가 
* 기존 '기준일ID'열에서 날짜 데이터를 추출하여 새로운 열로 추가 합니다.
    - pd.to_datetime() 함수를 사용해 '기준일ID'열을 datetime 형식으로 변경하겠습니다.
    - year, month, day 열로 기존 데이터 프레임에 연월일 정보를 저장합니다.
    - 데이터 프레임 열에 대해 날짜 정보를 얻을 때에는 **dt.year**, **dt.month**, **dt.day** 속성을 사용합니다.

In [308]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total['기준일ID']=pd.to_datetime(df_total['기준일ID'].astype('str'))

In [309]:
df_total.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,2017-01-01,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,1157.6661,1107.6781,1282.9235,1029.4360,998.0414,874.5643,1162.1547,1053.0477,964.3940,2025.4819
1,2017-01-01,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,...,1120.0051,1102.5198,1271.8997,1027.2574,1038.7528,857.9100,1149.7532,1042.7411,919.0115,2062.2422
2,2017-01-01,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,...,1103.1547,1112.4579,1282.9366,1027.8901,1020.0177,853.3890,1193.4472,1011.2073,889.9325,1960.1236
3,2017-01-01,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,...,1116.2165,1102.0668,1260.8472,1007.6650,1042.9554,896.0038,1163.0355,1056.6428,891.9177,2060.1872
4,2017-01-01,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,...,1187.5457,1120.2232,1281.2738,1064.0655,1045.2130,895.8336,1191.7017,1045.3362,874.4984,2038.6212

In [310]:
from datetime import date
df_total["년"] = [d.year for d in df_total["기준일ID"]]
df_total["월"] = [d.month for d in df_total["기준일ID"]]
df_total["일"] = [d.day for d in df_total["기준일ID"]]

In [311]:
df_test['기준일ID']=pd.to_datetime(df_test['기준일ID'].astype('str'))
df_test["년"] = [d.year for d in df_test["기준일ID"]]
df_test["월"] = [d.month for d in df_test["기준일ID"]]
df_test["일"] = [d.day for d in df_test["기준일ID"]]

In [312]:
df_test.tail()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일
4339,2022-06-30,19,32969.6040,2108.4754,613.9301,565.6419,904.1955,1338.8420,1416.2874,1785.9297,...,1315.6209,1221.7289,952.5630,1094.5123,932.6297,694.0737,1687.9623,2022,6,30
4340,2022-06-30,20,31014.6597,2017.9104,587.5599,542.7330,826.7983,1210.9392,1313.6926,1596.4043,...,1255.8520,1134.0779,906.4051,1016.0333,829.0177,693.8136,1679.0869,2022,6,30
4341,2022-06-30,21,30923.2923,2083.7634,606.7347,544.7149,813.5115,1175.5524,1279.7073,1659.6803,...,1236.1779,1113.2840,907.1416,1002.7494,835.7204,682.2879,1672.6951,2022,6,30
4342,2022-06-30,22,30509.5463,2186.0950,636.5307,573.6676,755.8347,1156.8269,1230.5487,1605.8491,...,1221.4595,1160.3239,879.1828,949.2953,821.7916,666.9312,1666.6319,2022,6,30
4343,2022-06-30,23,31184.8763,2179.2547,634.5390,580.9860,711.6332,1212.8320,1308.7377,1703.1838,...,1308.9829,1200.4453,840.6338,1001.2561,851.5886,716.4634,1761.5731,2022,6,30

#### [실습문제2] 불필요한 열 제거 및 열 이름 변경
* df_total과 df_test에서 '총생활인구수'외에 불필요한 열을 제거 하도록 하겠습니다.
* 시간 데이터를 남기고, '시간대구분' column 을 'hour'로 rename 하도록 하겠습니다.

In [313]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total.rename(columns={'시간대구분':'hour'},inplace=True)
df_test.rename(columns={'시간대구분':'hour'},inplace=True)

#### [실습문제3] 시프트 & 롤링
* shift()를 활용하여 이동할 행 수를 지정합니다.
* rolling()을 활용하여 추가할 이동평균 수를 지정합니다.

In [314]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# 1416 -> 이전 데이터로 1416시간 치의 예측치를 보겠다
df_total['2m'] = df_total['총생활인구수'].shift(1416)
df_total['1m'] = df_total['총생활인구수'].shift(708)
df_total['1d'] = df_total['총생활인구수'].shift(24)
df_total['1h'] = df_total['총생활인구수'].shift(1)
#df_total['2d_y'] = df_total['총생활인구수'].shift(24*7)

In [315]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_test['2m'] = df_test['총생활인구수'].shift(1416)
df_test['1m'] = df_test['총생활인구수'].shift(708)
df_test['1d'] = df_test['총생활인구수'].shift(24)
df_test['1h'] = df_test['총생활인구수'].shift(1)

In [316]:
df_total['2m_mean']=df_total['총생활인구수'].rolling(window=1416).mean()
df_test['2m_mean']=df_test['총생활인구수'].rolling(window=1416).mean()

In [293]:
df_total

,기준일ID,hour,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자65세부터69세생활인구수,여자70세이상생활인구수,년,월,일,2m,1m,1d,1h,2m_mean
0,2017-01-01,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,964.3940,2025.4819,2017,1,1,NaN,NaN,NaN,NaN,NaN
1,2017-01-01,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,...,919.0115,2062.2422,2017,1,1,NaN,NaN,NaN,31535.2200,NaN
2,2017-01-01,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,...,889.9325,1960.1236,2017,1,1,NaN,NaN,NaN,31188.9174,NaN
3,2017-01-01,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,...,891.9177,2060.1872,2017,1,1,NaN,NaN,NaN,31240.4974,NaN
4,2017-01-01,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,...,874.4984,2038.6212,2017,1,1,NaN,NaN,NaN,31442.4314,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43507,2021-12-31,19,33060.4555,1858.2611,541.0746,605.9080,781.6602,1342.6763,1435.1080,1678.8904,...,789.2094,1705.8216,2021,12,31,34554.6229,38689.1523,33928.2051,35883.1874,35421.033399
43508,2021-12-31,20,32360.1898,2093.8808,609.6807,612.5326,768.8351,1323.7124,1479.1382,1654.5005,...,792.1748,1726.3071,2021,12,31,33506.8350,40278.8698,33712.5348,33060.4555,35420.223622
43509,2021-12-31,21,31417.3991,1983.6728,577.5909,639.2174,779.6693,1187.6783,1375.6785,1600.9946,...,770.3955,1674.6047,2021,12,31,32323.8287,40520.3967,32144.4917,32360.1898,35419.583488
43510,2021-12-31,22,30763.0563,2028.3314,590.5941,654.0295,790.1638,1133.6311,1362.0266,1548.7366,...,753.9750,1727.0258,2021,12,31,31769.3180,40682.4584,32137.7017,31417.3991,35418.872851
43511,2021-12-31,23,30404.2740,1903.8825,554.3582,615.0753,772.8499,1136.6157,1295.0434,1549.1984,...,734.2503,1759.0664,2021,12,31,32503.2263,39822.0982,31641.1698,30763.0563,35417.390540

#### [실습문제4] 결측치 처리 및 불필요한 열 제거
* 롤링 & 시프트 과정에서 발생한 결측치를 처리하도록 하겠습니다.
* 불필요한 열을 추가로 제거 하겠습니다.(시간 관련 행들)

In [318]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# df_total.dropna(axis=0,inplace=True)
# df_test.dropna(axis=0,inplace=True)
df_total.fillna(df_total.mean(),inplace=True)
df_test.fillna(df_test.mean(),inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  """

In [319]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total.drop(labels='기준일ID',axis=1,inplace=True)
df_test.drop(labels='기준일ID',axis=1,inplace=True)

In [167]:
# df_total.drop(labels='총생활인구수',axis=1,inplace=True)
# df_test.drop(labels='총생활인구수',axis=1,inplace=True)

In [320]:
df_total.shape

(43512, 38)

In [321]:
df_test.shape

(4344, 38)

#### [실습문제5] train, test 데이터 나누기
* df_total과 df_test를 각각 train_x, train_y, test_x, test_y 로 나누어 주세요.
* 인덱스를 리셋 해주세요.

In [322]:
df=pd.concat([df_total,df_test])

In [323]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47856 entries, 0 to 4343
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   hour             47856 non-null  int64
 1   총생활인구수           47856 non-null  float64
 2   남자0세부터9세생활인구수    47856 non-null  float64
 3   남자10세부터14세생활인구수  47856 non-null  float64
 4   남자15세부터19세생활인구수  47856 non-null  float64
 5   남자20세부터24세생활인구수  47856 non-null  float64
 6   남자25세부터29세생활인구수  47856 non-null  float64
 7   남자30세부터34세생활인구수  47856 non-null  float64
 8   남자35세부터39세생활인구수  47856 non-null  float64
 9   남자40세부터44세생활인구수  47856 non-null  float64
 10  남자45세부터49세생활인구수  47856 non-null  float64
 11  남자50세부터54세생활인구수  47856 non-null  float64
 12  남자55세부터59세생활인구수  47856 non-null  float64
 13  남자60세부터64세생활인구수  47856 non-null  float64
 14  남자65세부터69세생활인구수  47856 non-null  float64
 15  남자70세이상생활인구수     47856 non-null  float64
 16  여자0세부터9세생활인구수    47856 non-null  float64
 17  여자10세부터14세생활인구수  47856 non-null  float64
 18  여자15세부터19세생활인구수  47856 non-null  float64
 19  여자20세부터24세생활인구수  47856 non-null  float64
 20  여자25세부터29세생활인구수  47856 non-null  float64
 21  여자30세부터34세생활인구수  47856 non-null  float64
 22  여자35세부터39세생활인구수  47856 non-null  float64
 23  여자40세부터44세생활인구수  47856 non-null  float64
 24  여자45세부터49세생활인구수  47856 non-null  float64
 25  여자50세부터54세생활인구수  47856 non-null  float64
 26  여자55세부터59세생활인구수  47856 non-null  float64
 27  여자60세부터64세생활인구수  47856 non-null  float64
 28  여자65세부터69세생활인구수  47856 non-null  float64
 29  여자70세이상생활인구수     47856 non-null  float64
 30  년                47856 non-null  int64
 31  월                47856 non-null  int64
 32  일                47856 non-null  int64
 33  2m               47856 non-null  float64
 34  1m               47856 non-null  float64
 35  1d               47856 non-null  float64
 36  1h               47856 non-null  float64
 37  2m_mean          47856 non-null  float64
dtypes: float64(34), int64(4)
memory usage: 14.2 MB

In [324]:
#x=df.drop(['y'],axis=1)
x=df[['hour','년','월','일','2m','1d','2m_mean','1h','1m']]
y=df.loc[:,'총생활인구수']

In [301]:
x

,hour,년,월,일,2m,1d,2m_mean,1h,1m
1416,0,2017,3,1,31535.2200,30693.4466,36436.655204,31021.6802,39933.0764
1417,1,2017,3,1,31188.9174,30895.3991,36436.051993,31209.1023,38605.3244
1418,2,2017,3,1,31240.4974,30876.0034,36435.570219,30334.7708,37762.3424
1419,3,2017,3,1,31442.4314,31090.4234,36435.108847,30558.3055,36779.9542
1420,4,2017,3,1,31922.7751,31564.4299,36434.754209,30789.1289,36108.9084
...,...,...,...,...,...,...,...,...,...
4339,19,2022,6,30,34399.1478,31689.8212,37846.469234,34644.2246,41039.1758
4340,20,2022,6,30,33072.9047,30425.9054,37845.015671,32969.6040,41457.5241
4341,21,2022,6,30,32823.1442,30352.8869,37843.673967,31014.6597,41644.5315
4342,22,2022,6,30,32271.0565,30232.2846,37842.429963,30923.2923,41273.2997
4343,23,2022,6,30,32947.6862,31251.4119,37841.185041,30509.5463,40885.7535

In [325]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = df_test.shape[0]-1, shuffle = False) #30 : 자연수 - 개수, shuffle : 섞어라

In [326]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
train_x.shape,test_x.shape

((43513, 9), (4343, 9))

In [327]:
test_x

,hour,년,월,일,2m,1d,2m_mean,1h,1m
1,1,2022,1,1,35115.409541,36007.123902,35861.341868,30509.7386,35613.888107
2,2,2022,1,1,35115.409541,36007.123902,35861.341868,30759.5067,35613.888107
3,3,2022,1,1,35115.409541,36007.123902,35861.341868,31048.8787,35613.888107
4,4,2022,1,1,35115.409541,36007.123902,35861.341868,31076.1092,35613.888107
5,5,2022,1,1,35115.409541,36007.123902,35861.341868,31714.9309,35613.888107
...,...,...,...,...,...,...,...,...,...
4339,19,2022,6,30,34399.147800,31689.821200,37846.469234,34644.2246,41039.175800
4340,20,2022,6,30,33072.904700,30425.905400,37845.015671,32969.6040,41457.524100
4341,21,2022,6,30,32823.144200,30352.886900,37843.673967,31014.6597,41644.531500
4342,22,2022,6,30,32271.056500,30232.284600,37842.429963,30923.2923,41273.299700
4343,23,2022,6,30,32947.686200,31251.411900,37841.185041,30509.5463,40885.753500

---

## 다음 단계를 위해서 데이터를 저장하겠습니다.

In [329]:
# CSV로 저장
train_x.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/train_x.csv', index = False)
train_y.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/train_y.csv', index = False)
test_x.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test_x.csv', index = False)
test_y.to_csv('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test_y.csv', index = False)

---