# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

In [64]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

---

# (실습준비) 데이터 불러오기부터

In [746]:
import pandas as pd

# 학습/평가 데이터 로딩
train_x = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/train_x.csv")
train_y = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/train_y.csv")
test_x = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test_x.csv")
test_y = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/test_y.csv")

In [747]:
acc_test_x=train_x[-1416:]

In [748]:
acc_test_x

               1d          1h          1m      총생활인구수        2m1d        2m7d
39096  40844.0424  39239.6609  41081.4210  39344.5300  40095.0964  41194.5851
39097  40635.2950  39344.5300  40982.3694  39092.8105  40010.9562  40980.5840
39098  40439.3407  39092.8105  40823.5553  39044.0701  39918.0496  40901.9228
39099  40338.1786  39044.0701  40857.8071  38895.5915  39769.1474  40803.7674
39100  40312.9573  38895.5915  40933.0451  38884.0841  39770.9354  40767.5235
...           ...         ...         ...         ...         ...         ...
40507  36087.9937  35189.4563  36116.6066  35708.4819  36550.1959  36679.0610
40508  36339.3987  35708.4819  36134.3644  35924.7026  36875.3016  36690.0584
40509  36527.5722  35924.7026  36188.5522  36597.7205  37537.6841  36379.8533
40510  36940.6312  36597.7205  37142.7382  37163.4665  37773.6538  36455.7181
40511  40458.3040  37163.4665  40158.2582  39853.9949  40546.8265  39002.5907

[1416 rows x 6 columns]

In [749]:
acc_test_y=test_y[:1416]

In [750]:
a=list(train_x)
b=(test_x)

In [751]:
train_x = train_x.values
train_y = train_y.values
test_x = test_x.values
test_y = test_y.values

---

# 1. Machine Learning
## 이제 모델링을 해봅시다!
+ KeyPoint : 머신러닝 라이브러리를 토대로 모델링을 할 수 있다.

In [627]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='Malgun Gothic')
sns.set(font="Malgun Gothic",#"NanumGothicCoding", 
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')

### 가. LinearRegression 부터 시작해봅시다.

#### [실습문제1] 머신러닝_1
* Train과 Test로 나눈 데이터를 기준으로 LinearRegression 모델링을 진행하고 평가를 해주세요.
* 성능지표 : RMSE, R-squared Score

In [730]:
# 아래에 실습코드를 작성하세요.
from sklearn.linear_model import LinearRegression
from sklearn.metrics import *

In [752]:
# 아래에 실습코드를 작성하세요.
linear=LinearRegression()
linear.fit(train_x,train_y)
linear_predict=linear.predict(acc_test_x)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [754]:
# 아래에 실습코드를 작성하세요.
print('RMSE : ', mean_squared_error(acc_test_y, linear_predict, squared = False))
print('R2score  : ', r2_score(acc_test_y, linear_predict))

RMSE :  1543.8790160065723
R2score  :  0.4006295941082473

### 나. 다음은 앙상블 기법을 토대로 랜덤포레스트와 그라디언부스팅을 활용해봅시다.

#### 1) 렌덤포레스트
##### 배깅의 일종으로 의사결정나무(Decision Tree) 여러 개를 모아서 숲을 랜덤으로 구성하고 이를 종합해서 최종 모델을 산출하는 기법이라고 할 수 있다.

#### [실습문제2] 머신러닝_2
* Train과 Test로 나눈 데이터를 기준으로 렌덤포레스트로 모델을 학습을 진행하고 평가를 해주세요.
* 성능지표 : RMSE, R-squared Score

In [676]:
# 아래에 실습코드를 작성하세요.
from sklearn.ensemble import RandomForestRegressor
params={'n_estimators': range(60,200,10),'max_features':range(1,7,2)}
rf=RandomForestRegressor()
rf_gs=GridSearchCV(rf,params,cv=5,verbose=3)
rf.fit(train_x,train_y)
rf_predict=rf.predict(test_x)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [677]:
rf_predict=rf.predict(acc_test_x)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [678]:
# 아래에 실습코드를 작성하세요.
print('RMSE : ', mean_squared_error(acc_test_y, rf_predict, squared = False))
print('R2score  : ', r2_score(acc_test_y, rf_predict))

RMSE :  1462.909754862829
R2score  :  0.4618493879539398

#### [실습문제3] 머신러닝_3
* 렌덤포레스트로 학습한 모델의 feature_importances 또는 Shap value를 구해보세요.
* 확인할 수 있는 내용으로 우리 모델에서의 인사이트를 정리해보세요.

In [ ]:
# Feature의 중요도 확인
# 변수 중요도 plot
def plot_feature_importance(importance, names, topn = 'all'):
    feature_importance = np.array(importance)
    feature_names = np.array(names)

    data={'feature_names':feature_names,'feature_importance':feature_importance}
    fi_temp = pd.DataFrame(data)

    fi_temp.sort_values(by=['feature_importance'], ascending=False,inplace=True)
    fi_temp.reset_index(drop=True, inplace = True)

    if topn == 'all' :
        fi_df = fi_temp.copy()
    else :
        fi_df = fi_temp.iloc[:topn]

    plt.figure(figsize=(10,8))
    sns.barplot(x='feature_importance', y='feature_names', data = fi_df)

    plt.xlabel('importance')
    plt.ylabel('feature names')
    plt.grid()

    return fi_df

In [ ]:
from sklearn.tree import DecisionTreeRegressor, plot_tree
import numpy as np
from sklearn.inspection import permutation_importance

In [499]:
result = plot_feature_importance(rf_gs.best_estimator_.feature_importances_, a, 6)

NameError: ignored

In [ ]:
# 확인할 수 있는 인사이트
# 1.
# 2.
# 3.

#### 2) GradientBoosting
##### 앞선 모델의 에러를 다음 모델의 예측 값으로 활용하면서 가중치 업데이트 하는데 경사하강법(Gradient Descent)를 활용해서 최적 모델을 만드는 기법

#### [실습문제4] 머신러닝_4
* Train과 Test로 나눈 데이터를 기준으로 그라디언트부스팅으로 모델을 학습을 진행하고 평가를 해주세요.
* 성능지표 : RMSE, R-squared Score

In [755]:
# 아래에 실습코드를 작성하세요.
from sklearn.ensemble import GradientBoostingRegressor

gb=GradientBoostingRegressor()
gb.fit(train_x,train_y)
gb_predict=gb.predict(test_x)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [756]:
gb_predict=gb.predict(acc_test_x)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but GradientBoostingRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

In [757]:
# 아래에 실습코드를 작성하세요.
# 아래에 실습코드를 작성하세요.
print('RMSE : ', mean_squared_error(acc_test_y, gb_predict, squared = False))
print('R2score  : ', r2_score(acc_test_y, gb_predict))

RMSE :  1526.335178198893
R2score  :  0.41417406504626975

#### [실습문제5] 머신러닝_5
* 그라디언트부스팅으로 학습한 모델의 feature_importances 또는 Shap value를 구해보세요.
* 확인할 수 있는 내용으로 우리 모델에서의 인사이트를 정리해보세요.

In [ ]:
# Feature의 중요도 확인

In [ ]:
# 확인할 수 있는 인사이트
# 1.
# 2.
# 3.

#### 3) Self Choice Model
##### 앞선 교육과정에서 배운 머신러닝 모델 중 어떤 것이든 좋습니다. 원하는 모델을 선택해서 학습을 시켜보세요.

#### [실습문제6] 머신러닝_6
* Train과 Test로 나눈 데이터를 기준으로 Self Choice Model로 모델을 학습을 진행하고 평가를 해주세요.
* 성능지표 : RMSE, R-squared Score

In [320]:
# 아래에 실습코드를 작성하세요.
from sklearn.svm import SVC,SVR
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from xgboost import XGBRegressor

In [666]:
# 아래에 실습코드를 작성하세요.
parmas={'max_depth':range(5,7,1),'n_estimators':range(100,120,10),'learning_rate':[0.1,0.2,0.3]}
xgb=XGBRegressor()
xgb_gs=GridSearchCV(xgb,parmas)
xgb_gs.fit(train_x,train_y)
xgb_predict=xgb_gs.predict(acc_test_x)

[06:12:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:11] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:13] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:20] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:22] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:25] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:27] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:36] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:39] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:42] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:44] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:47] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:50] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:52] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:12:58] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:01] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:03] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:05] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:07] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:12] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:14] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:16] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:19] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:21] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:24] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:26] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:29] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:31] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:34] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:37] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:39] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:42] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:51] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:53] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:13:57] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:00] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:02] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:04] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:06] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:11] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:14] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:16] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:19] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:22] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:24] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:27] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:33] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:38] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[06:14:41] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

ValueError: ignored

In [498]:
# 아래에 실습코드를 작성하세요.
print('RMSE : ', mean_squared_error(acc_test_y, xgb_predict, squared = False))
print('R2score  : ', r2_score(acc_test_y, xgb_predict))

RMSE :  1454.0711848806397
R2score  :  0.46833251247452923

In [457]:
xgb_gs.best_params_

{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}

In [ ]:
import joblib
joblib.dump(xgb_gs,'/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/model/xgb.pkl')

['/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/model/xgb.pkl']

#### [실습문제7] 머신러닝_7
* Self Choice Model로 학습한 모델의 feature_importances 또는 Shap value를 구해보세요.
* 확인할 수 있는 내용으로 우리 모델에서의 인사이트를 정리해보세요.

In [ ]:
# Feature의 중요도 확인

In [ ]:
# 확인할 수 있는 인사이트
# 1.
# 2.
# 3.

#### [실습문제8] 스케일링
* Min Max Scale 함수를 활용하여 스케일링 후 위 모델에 적용하여 보세요.

In [383]:
# 아래에 실습코드를 작성하세요.
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
train_x_s=scaler.fit_transform(train_x)
test_x_s=scaler.transform(test_x)

In [ ]:
# 아래에 실습코드를 작성하세요.

In [328]:
result=test_y[:1416]

---

# 2. Deep Learning 
## 이번엔 딥러닝 모델링을 해봅시다.

#### [실습문제9] 딥러닝

* tensorflow 라이브러리를 활용한 모델을 자유롭게 만들어보세요.

In [11]:
# 아래에 실습코드를 작성하세요.
import tensorflow as tf
from tensorflow import keras

In [736]:
train_x.shape

(40512, 35)

In [738]:
# 아래에 실습코드를 작성하세요.
keras.backend.clear_session()

dl=keras.models.Sequential()
dl.add(keras.layers.Input(shape=(35,)))
dl.add(keras.layers.Dense(256,activation='swish'))
dl.add(keras.layers.Dense(1))

dl.compile(loss='mse',optimizer='adam')
dl.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 256)               9216

 dense_1 (Dense)             (None, 1)                 257

=================================================================
Total params: 9,473
Trainable params: 9,473
Non-trainable params: 0
_________________________________________________________________

In [739]:
from tensorflow.keras.callbacks import EarlyStopping
es=EarlyStopping(monitor='val_loss',
                 min_delta=0,
                 patience=5,
                 verbose=1,
                 restore_best_weights=True)

In [740]:
# 아래에 실습코드를 작성하세요.
dl.fit(train_x,train_y,epochs=100, validation_split=0.2,callbacks=[es])

Epoch 1/100
1013/1013 [==============================] - 3s 3ms/step - loss: 5686795.5000 - val_loss: 106899.2188
Epoch 2/100
1013/1013 [==============================] - 2s 2ms/step - loss: 88198.6562 - val_loss: 8825.7080
Epoch 3/100
1013/1013 [==============================] - 2s 2ms/step - loss: 6994.6089 - val_loss: 1222.1027
Epoch 4/100
1013/1013 [==============================] - 2s 2ms/step - loss: 2447.6367 - val_loss: 408.7834
Epoch 5/100
1013/1013 [==============================] - 2s 2ms/step - loss: 5661.1802 - val_loss: 18360.9258
Epoch 6/100
1013/1013 [==============================] - 2s 2ms/step - loss: 11680.3301 - val_loss: 1514.7332
Epoch 7/100
1013/1013 [==============================] - 2s 2ms/step - loss: 17814.0508 - val_loss: 3910.8193
Epoch 8/100
1013/1013 [==============================] - 2s 2ms/step - loss: 14402.5107 - val_loss: 46294.4492
Epoch 9/100
1004/1013 [============================>.] - ETA: 0s - loss: 14617.9092Restoring model weights from the end of the best epoch: 4.
1013/1013 [==============================] - 2s 2ms/step - loss: 14985.8369 - val_loss: 52471.8828
Epoch 9: early stopping

In [741]:
# 아래에 실습코드를 작성하세요.
dl_predict=dl.predict(acc_test_x)
print('RMSE : ', mean_squared_error(acc_test_y, dl_predict, squared = False))
print('R2score  : ', r2_score(acc_test_y, dl_predict))

45/45 [==============================] - 0s 1ms/step
RMSE :  1640.1960784109635
R2score  :  0.323511675943697

In [ ]:
# 아래에 실습코드를 작성하세요.

In [ ]:
# 아래에 실습코드를 작성하세요.

In [79]:
import joblib

In [397]:
xgb=joblib.load('/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/model/xgb.pkl')

[05:16:06] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

In [696]:
result=dl.predict(test_x)

45/45 [==============================] - 0s 1ms/step

In [697]:
result=pd.DataFrame(result)

In [698]:
result

                 0
0     40825.375000
1     40611.847656
2     40557.191406
3     40554.398438
4     40614.382812
...            ...
1411  34202.363281
1412  34528.460938
1413  35183.722656
1414  35505.996094
1415  38120.699219

[1416 rows x 1 columns]

## 정리

1. 스케일링 시 성능 하락
2. 총생활인구 drop, 성별나이 살리면 성능 0.95까지 나옴
3. 튜토리얼시 최고 성능 0.72
4. 총생활인구 y, 1d,1h,2m x  최고성능 Gradient Boosting 0.96
5. 총생활인구 y, 1d,1h,2m,1m,2m_mean x  최고성능 Gradient Boosting 0.96 model save

## kaggle 작업

In [348]:
## kaggle 작업
result=pd.DataFrame(linear_predict)

In [349]:
result=result.iloc[:1416]

In [699]:
b=range(0,1416)

In [700]:
result["id"]=b

In [701]:
result.rename(columns={0:'count'},inplace=True)

In [702]:
result

             count    id
0     40825.375000     0
1     40611.847656     1
2     40557.191406     2
3     40554.398438     3
4     40614.382812     4
...            ...   ...
1411  34202.363281  1411
1412  34528.460938  1412
1413  35183.722656  1413
1414  35505.996094  1414
1415  38120.699219  1415

[1416 rows x 2 columns]

In [703]:
result=result[["id","count"]]

In [704]:
result

        id         count
0        0  40825.375000
1        1  40611.847656
2        2  40557.191406
3        3  40554.398438
4        4  40614.382812
...    ...           ...
1411  1411  34202.363281
1412  1412  34528.460938
1413  1413  35183.722656
1414  1414  35505.996094
1415  1415  38120.699219

[1416 rows x 2 columns]

In [705]:
result.to_csv("/content/drive/MyDrive/Colab Notebooks/aivle/5차미니프로젝트-개인/kaggle/result.csv",index=False)