In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import fetch_california_housing

## 문제1

### data load

In [2]:
data=fetch_california_housing()

In [3]:
x=data.data
y=data.target

In [6]:
x.shape,y.shape

((20640, 8), (20640,))

In [9]:
pd.DataFrame(x,columns=data.feature_names).head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [11]:
pd.DataFrame(y,columns=data.target_names).head()

   MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

### 전처리

In [13]:
print(data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

An household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surpinsingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. topic:: References

    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
      Statistics and Probability Letters, 33 (1997) 291-297

In [51]:
pd.DataFrame(x,columns=data.feature_names).describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [52]:
pd.DataFrame(x,columns=data.feature_names).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [15]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,Dense,Flatten
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2022,test_size=0.2)

In [18]:
x_train.shape,y_train.shape

((16512, 8), (16512,))

In [53]:
from sklearn.preprocessing import MinMaxScaler

In [54]:
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

### 모델링

In [55]:
keras.backend.clear_session()
model=keras.models.Sequential()
model.add(Input(shape=(8,)))
model.add(Dense(16,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                144

 dense_1 (Dense)             (None, 32)                544

 dense_2 (Dense)             (None, 64)                2112

 dense_3 (Dense)             (None, 128)               8320

 dense_4 (Dense)             (None, 256)               33024

 dense_5 (Dense)             (None, 1)                 257

=================================================================
Total params: 44,401
Trainable params: 44,401
Non-trainable params: 0
_________________________________________________________________

In [56]:
model.compile(loss='mse',optimizer="adam")

In [46]:
from tensorflow.keras.callbacks import EarlyStopping

In [47]:
es=EarlyStopping(monitor='val_loss',verbose=1,min_delta=0,patience=7,restore_best_weights=True)

In [57]:
model.fit(x_train,y_train,verbose=1,validation_split=0.3,callbacks=[es],epochs=500)

Epoch 1/500
362/362 [==============================] - 2s 3ms/step - loss: 0.8403 - val_loss: 0.5637
Epoch 2/500
362/362 [==============================] - 1s 3ms/step - loss: 0.5409 - val_loss: 0.5694
Epoch 3/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4982 - val_loss: 0.5001
Epoch 4/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4708 - val_loss: 0.4774
Epoch 5/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4562 - val_loss: 0.4712
Epoch 6/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4386 - val_loss: 0.4356
Epoch 7/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4251 - val_loss: 0.4685
Epoch 8/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4090 - val_loss: 0.4090
Epoch 9/500
362/362 [==============================] - 1s 3ms/step - loss: 0.4030 - val_loss: 0.4090
Epoch 10/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3904 - val_loss: 0.3970
Epoch 11/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3941 - val_loss: 0.4010
Epoch 12/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3797 - val_loss: 0.3789
Epoch 13/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3721 - val_loss: 0.4115
Epoch 14/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3706 - val_loss: 0.4862
Epoch 15/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3725 - val_loss: 0.3854
Epoch 16/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3686 - val_loss: 0.3724
Epoch 17/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3588 - val_loss: 0.3495
Epoch 18/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3584 - val_loss: 0.3485
Epoch 19/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3508 - val_loss: 0.3521
Epoch 20/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3451 - val_loss: 0.4524
Epoch 21/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3522 - val_loss: 0.3639
Epoch 22/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3566 - val_loss: 0.3588
Epoch 23/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3386 - val_loss: 0.3549
Epoch 24/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3344 - val_loss: 0.3780
Epoch 25/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3387 - val_loss: 0.3468
Epoch 26/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3338 - val_loss: 0.3947
Epoch 27/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3309 - val_loss: 0.3653
Epoch 28/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3283 - val_loss: 0.3905
Epoch 29/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3322 - val_loss: 0.3555
Epoch 30/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3259 - val_loss: 0.3463
Epoch 31/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3276 - val_loss: 0.3419
Epoch 32/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3247 - val_loss: 0.3565
Epoch 33/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3259 - val_loss: 0.3534
Epoch 34/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3115 - val_loss: 0.3656
Epoch 35/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3255 - val_loss: 0.3424
Epoch 36/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3090 - val_loss: 0.3411
Epoch 37/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3141 - val_loss: 0.3294
Epoch 38/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3106 - val_loss: 0.3448
Epoch 39/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3115 - val_loss: 0.3480
Epoch 40/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3042 - val_loss: 0.3552
Epoch 41/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3069 - val_loss: 0.3206
Epoch 42/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3062 - val_loss: 0.3907
Epoch 43/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3198 - val_loss: 0.3496
Epoch 44/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3030 - val_loss: 0.4526
Epoch 45/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3013 - val_loss: 0.3304
Epoch 46/500
362/362 [==============================] - 1s 4ms/step - loss: 0.3065 - val_loss: 0.3456
Epoch 47/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2917 - val_loss: 0.3082
Epoch 48/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3054 - val_loss: 0.3410
Epoch 49/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3052 - val_loss: 0.3107
Epoch 50/500
362/362 [==============================] - 1s 3ms/step - loss: 0.3050 - val_loss: 0.3202
Epoch 51/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2948 - val_loss: 0.3012
Epoch 52/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2889 - val_loss: 0.3207
Epoch 53/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2931 - val_loss: 0.3059
Epoch 54/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2901 - val_loss: 0.3140
Epoch 55/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2954 - val_loss: 0.3247
Epoch 56/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2941 - val_loss: 0.3003
Epoch 57/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2893 - val_loss: 0.3516
Epoch 58/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2878 - val_loss: 0.3118
Epoch 59/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2908 - val_loss: 0.3307
Epoch 60/500
362/362 [==============================] - 2s 4ms/step - loss: 0.2932 - val_loss: 0.3443
Epoch 61/500
362/362 [==============================] - 2s 5ms/step - loss: 0.2870 - val_loss: 0.3117
Epoch 62/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2841 - val_loss: 0.3016
Epoch 63/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2876 - val_loss: 0.2874
Epoch 64/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2820 - val_loss: 0.2908
Epoch 65/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2854 - val_loss: 0.3043
Epoch 66/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2843 - val_loss: 0.3485
Epoch 67/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2862 - val_loss: 0.3012
Epoch 68/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2817 - val_loss: 0.3316
Epoch 69/500
362/362 [==============================] - 1s 3ms/step - loss: 0.2803 - val_loss: 0.3030
Epoch 70/500
358/362 [============================>.] - ETA: 0s - loss: 0.2853Restoring model weights from the end of the best epoch: 63.
362/362 [==============================] - 1s 3ms/step - loss: 0.2852 - val_loss: 0.2989
Epoch 70: early stopping

In [58]:
pred=model.predict(x_test)

In [59]:
pred[:5].reshape(-1)

array([4.7036057, 1.4990048, 1.3539822, 0.9399331, 2.8430917],
      dtype=float32)

In [60]:
y_test[:5]

array([4.771, 1.371, 1.233, 0.938, 3.26 ])

## 문제2

### data load

In [61]:
from sklearn.datasets import load_wine

In [62]:
wine=load_wine()

In [64]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2

    :Summary Statistics:

    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners:

Forina, M. et al, PARVUS -
An Extendible Package for Data Exploration, Classification and Correlation.
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science.

.. topic:: References

  (1) S. Aeberhard, D. Coomans and O. de Vel,
  Comparison of Classifiers in High Dimensional Settings,
  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Technometrics).

  The data was used with many others for comparing various
  classifiers. The classes are separable, though only RDA
  has achieved 100% correct classification.
  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data))
  (All results using the leave-one-out technique)

  (2) S. Aeberhard, D. Coomans and O. de Vel,
  "THE CLASSIFICATION PERFORMANCE OF RDA"
  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of
  Mathematics and Statistics, James Cook University of North Queensland.
  (Also submitted to Journal of Chemometrics).

In [78]:
x=wine.data
y=wine.target

In [79]:
pd.DataFrame(x,columns=wine.feature_names).head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [80]:
pd.DataFrame(x,columns=wine.feature_names).describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [81]:
x.shape,y.shape

((178, 13), (178,))

### 전처리

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2022,test_size=0.2)

In [75]:
from tensorflow.keras.utils import to_categorical

In [84]:
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [85]:
y_train = to_categorical(y_train, 3)
y_test = to_categorical(y_test, 3)

### 모델링

In [101]:
keras.backend.clear_session()
il=keras.layers.Input(shape=(13,))
hl=keras.layers.Dense(8,activation='relu')(il)
hl=keras.layers.Dense(16,activation='relu')(hl)
hl=keras.layers.Dense(32,activation='relu')(hl)
ol=keras.layers.Dense(3,activation='sigmoid')(il)
model=keras.models.Model(inputs=il,outputs=ol)
model.compile(metrics=['accuracy'],optimizer='adam',loss=keras.losses.categorical_crossentropy)

In [102]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 13)]              0

 dense_3 (Dense)             (None, 3)                 42

=================================================================
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________

In [103]:
es=EarlyStopping(verbose=1,patience=5,min_delta=0,restore_best_weights=True,monitor='val_loss')

In [104]:
model.fit(x_train,y_train,verbose=1,callbacks=[es],validation_split=0.1,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 53ms/step - loss: 1.2761 - accuracy: 0.3622 - val_loss: 1.1383 - val_accuracy: 0.5333
Epoch 2/100
4/4 [==============================] - 0s 9ms/step - loss: 1.2620 - accuracy: 0.3780 - val_loss: 1.1248 - val_accuracy: 0.5333
Epoch 3/100
4/4 [==============================] - 0s 9ms/step - loss: 1.2481 - accuracy: 0.3937 - val_loss: 1.1120 - val_accuracy: 0.5333
Epoch 4/100
4/4 [==============================] - 0s 9ms/step - loss: 1.2348 - accuracy: 0.4016 - val_loss: 1.0997 - val_accuracy: 0.5333
Epoch 5/100
4/4 [==============================] - 0s 10ms/step - loss: 1.2225 - accuracy: 0.4252 - val_loss: 1.0874 - val_accuracy: 0.6000
Epoch 6/100
4/4 [==============================] - 0s 9ms/step - loss: 1.2107 - accuracy: 0.4331 - val_loss: 1.0752 - val_accuracy: 0.6000
Epoch 7/100
4/4 [==============================] - 0s 9ms/step - loss: 1.1992 - accuracy: 0.4409 - val_loss: 1.0632 - val_accuracy: 0.6000
Epoch 8/100
4/4 [==============================] - 0s 9ms/step - loss: 1.1861 - accuracy: 0.4488 - val_loss: 1.0518 - val_accuracy: 0.6000
Epoch 9/100
4/4 [==============================] - 0s 9ms/step - loss: 1.1749 - accuracy: 0.4724 - val_loss: 1.0407 - val_accuracy: 0.6000
Epoch 10/100
4/4 [==============================] - 0s 8ms/step - loss: 1.1636 - accuracy: 0.4961 - val_loss: 1.0300 - val_accuracy: 0.6000
Epoch 11/100
4/4 [==============================] - 0s 8ms/step - loss: 1.1528 - accuracy: 0.5039 - val_loss: 1.0196 - val_accuracy: 0.6000
Epoch 12/100
4/4 [==============================] - 0s 10ms/step - loss: 1.1416 - accuracy: 0.5118 - val_loss: 1.0099 - val_accuracy: 0.6000
Epoch 13/100
4/4 [==============================] - 0s 8ms/step - loss: 1.1316 - accuracy: 0.5197 - val_loss: 1.0003 - val_accuracy: 0.6000
Epoch 14/100
4/4 [==============================] - 0s 15ms/step - loss: 1.1214 - accuracy: 0.5197 - val_loss: 0.9910 - val_accuracy: 0.6000
Epoch 15/100
4/4 [==============================] - 0s 10ms/step - loss: 1.1112 - accuracy: 0.5197 - val_loss: 0.9820 - val_accuracy: 0.6000
Epoch 16/100
4/4 [==============================] - 0s 8ms/step - loss: 1.1024 - accuracy: 0.5354 - val_loss: 0.9731 - val_accuracy: 0.6000
Epoch 17/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0934 - accuracy: 0.5354 - val_loss: 0.9645 - val_accuracy: 0.6000
Epoch 18/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0840 - accuracy: 0.5433 - val_loss: 0.9566 - val_accuracy: 0.6000
Epoch 19/100
4/4 [==============================] - 0s 12ms/step - loss: 1.0755 - accuracy: 0.5512 - val_loss: 0.9487 - val_accuracy: 0.6000
Epoch 20/100
4/4 [==============================] - 0s 10ms/step - loss: 1.0668 - accuracy: 0.5512 - val_loss: 0.9413 - val_accuracy: 0.6000
Epoch 21/100
4/4 [==============================] - 0s 8ms/step - loss: 1.0590 - accuracy: 0.5512 - val_loss: 0.9338 - val_accuracy: 0.6000
Epoch 22/100
4/4 [==============================] - 0s 10ms/step - loss: 1.0515 - accuracy: 0.5512 - val_loss: 0.9265 - val_accuracy: 0.6000
Epoch 23/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0434 - accuracy: 0.5433 - val_loss: 0.9195 - val_accuracy: 0.6000
Epoch 24/100
4/4 [==============================] - 0s 10ms/step - loss: 1.0361 - accuracy: 0.5433 - val_loss: 0.9129 - val_accuracy: 0.6000
Epoch 25/100
4/4 [==============================] - 0s 11ms/step - loss: 1.0290 - accuracy: 0.5433 - val_loss: 0.9068 - val_accuracy: 0.6000
Epoch 26/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0221 - accuracy: 0.5354 - val_loss: 0.9008 - val_accuracy: 0.6000
Epoch 27/100
4/4 [==============================] - 0s 15ms/step - loss: 1.0152 - accuracy: 0.5354 - val_loss: 0.8947 - val_accuracy: 0.6000
Epoch 28/100
4/4 [==============================] - 0s 8ms/step - loss: 1.0094 - accuracy: 0.5433 - val_loss: 0.8891 - val_accuracy: 0.6000
Epoch 29/100
4/4 [==============================] - 0s 9ms/step - loss: 1.0022 - accuracy: 0.5433 - val_loss: 0.8837 - val_accuracy: 0.6000
Epoch 30/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9964 - accuracy: 0.5433 - val_loss: 0.8783 - val_accuracy: 0.6000
Epoch 31/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9903 - accuracy: 0.5433 - val_loss: 0.8728 - val_accuracy: 0.6667
Epoch 32/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9848 - accuracy: 0.5512 - val_loss: 0.8675 - val_accuracy: 0.6667
Epoch 33/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9790 - accuracy: 0.5669 - val_loss: 0.8623 - val_accuracy: 0.7333
Epoch 34/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9733 - accuracy: 0.5827 - val_loss: 0.8573 - val_accuracy: 0.7333
Epoch 35/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9680 - accuracy: 0.5906 - val_loss: 0.8527 - val_accuracy: 0.7333
Epoch 36/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9630 - accuracy: 0.5906 - val_loss: 0.8479 - val_accuracy: 0.7333
Epoch 37/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9580 - accuracy: 0.5984 - val_loss: 0.8433 - val_accuracy: 0.7333
Epoch 38/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9527 - accuracy: 0.5906 - val_loss: 0.8389 - val_accuracy: 0.7333
Epoch 39/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9478 - accuracy: 0.6063 - val_loss: 0.8347 - val_accuracy: 0.8000
Epoch 40/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9433 - accuracy: 0.6142 - val_loss: 0.8303 - val_accuracy: 0.8000
Epoch 41/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9384 - accuracy: 0.6142 - val_loss: 0.8260 - val_accuracy: 0.8000
Epoch 42/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9343 - accuracy: 0.6220 - val_loss: 0.8218 - val_accuracy: 0.8000
Epoch 43/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9295 - accuracy: 0.6457 - val_loss: 0.8178 - val_accuracy: 0.8000
Epoch 44/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9254 - accuracy: 0.6457 - val_loss: 0.8140 - val_accuracy: 0.8000
Epoch 45/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9209 - accuracy: 0.6457 - val_loss: 0.8101 - val_accuracy: 0.8000
Epoch 46/100
4/4 [==============================] - 0s 9ms/step - loss: 0.9166 - accuracy: 0.6535 - val_loss: 0.8063 - val_accuracy: 0.8000
Epoch 47/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9127 - accuracy: 0.6535 - val_loss: 0.8027 - val_accuracy: 0.8000
Epoch 48/100
4/4 [==============================] - 0s 8ms/step - loss: 0.9084 - accuracy: 0.6535 - val_loss: 0.7990 - val_accuracy: 0.8667
Epoch 49/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9044 - accuracy: 0.6535 - val_loss: 0.7951 - val_accuracy: 0.8667
Epoch 50/100
4/4 [==============================] - 0s 10ms/step - loss: 0.9005 - accuracy: 0.6535 - val_loss: 0.7913 - val_accuracy: 0.8667
Epoch 51/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8965 - accuracy: 0.6614 - val_loss: 0.7877 - val_accuracy: 0.8667
Epoch 52/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8927 - accuracy: 0.6850 - val_loss: 0.7841 - val_accuracy: 0.8667
Epoch 53/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8891 - accuracy: 0.6850 - val_loss: 0.7807 - val_accuracy: 0.8667
Epoch 54/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8854 - accuracy: 0.6850 - val_loss: 0.7774 - val_accuracy: 0.8667
Epoch 55/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8816 - accuracy: 0.6929 - val_loss: 0.7739 - val_accuracy: 0.8667
Epoch 56/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8779 - accuracy: 0.6929 - val_loss: 0.7702 - val_accuracy: 0.8667
Epoch 57/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8744 - accuracy: 0.7087 - val_loss: 0.7672 - val_accuracy: 0.8667
Epoch 58/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8707 - accuracy: 0.7087 - val_loss: 0.7637 - val_accuracy: 0.8667
Epoch 59/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8671 - accuracy: 0.7087 - val_loss: 0.7604 - val_accuracy: 0.8667
Epoch 60/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8637 - accuracy: 0.7087 - val_loss: 0.7573 - val_accuracy: 0.8667
Epoch 61/100
4/4 [==============================] - 0s 16ms/step - loss: 0.8605 - accuracy: 0.7244 - val_loss: 0.7542 - val_accuracy: 0.8667
Epoch 62/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8567 - accuracy: 0.7244 - val_loss: 0.7508 - val_accuracy: 0.8667
Epoch 63/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8534 - accuracy: 0.7480 - val_loss: 0.7475 - val_accuracy: 0.8667
Epoch 64/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8500 - accuracy: 0.7480 - val_loss: 0.7442 - val_accuracy: 0.8667
Epoch 65/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8468 - accuracy: 0.7559 - val_loss: 0.7412 - val_accuracy: 0.8667
Epoch 66/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8434 - accuracy: 0.7874 - val_loss: 0.7380 - val_accuracy: 0.8667
Epoch 67/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8402 - accuracy: 0.7953 - val_loss: 0.7350 - val_accuracy: 0.8667
Epoch 68/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8369 - accuracy: 0.8031 - val_loss: 0.7320 - val_accuracy: 0.8667
Epoch 69/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8337 - accuracy: 0.8031 - val_loss: 0.7290 - val_accuracy: 0.8667
Epoch 70/100
4/4 [==============================] - 0s 8ms/step - loss: 0.8305 - accuracy: 0.8110 - val_loss: 0.7259 - val_accuracy: 0.8667
Epoch 71/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8273 - accuracy: 0.8110 - val_loss: 0.7231 - val_accuracy: 0.8667
Epoch 72/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8243 - accuracy: 0.8268 - val_loss: 0.7202 - val_accuracy: 0.8667
Epoch 73/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8211 - accuracy: 0.8268 - val_loss: 0.7174 - val_accuracy: 0.8667
Epoch 74/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8181 - accuracy: 0.8268 - val_loss: 0.7148 - val_accuracy: 0.8667
Epoch 75/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8149 - accuracy: 0.8268 - val_loss: 0.7118 - val_accuracy: 0.8667
Epoch 76/100
4/4 [==============================] - 0s 10ms/step - loss: 0.8119 - accuracy: 0.8346 - val_loss: 0.7089 - val_accuracy: 0.8667
Epoch 77/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8089 - accuracy: 0.8346 - val_loss: 0.7061 - val_accuracy: 0.9333
Epoch 78/100
4/4 [==============================] - 0s 11ms/step - loss: 0.8058 - accuracy: 0.8425 - val_loss: 0.7032 - val_accuracy: 0.9333
Epoch 79/100
4/4 [==============================] - 0s 9ms/step - loss: 0.8029 - accuracy: 0.8425 - val_loss: 0.7003 - val_accuracy: 0.9333
Epoch 80/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7998 - accuracy: 0.8425 - val_loss: 0.6975 - val_accuracy: 0.9333
Epoch 81/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7970 - accuracy: 0.8504 - val_loss: 0.6949 - val_accuracy: 0.9333
Epoch 82/100
4/4 [==============================] - 0s 13ms/step - loss: 0.7939 - accuracy: 0.8504 - val_loss: 0.6920 - val_accuracy: 0.9333
Epoch 83/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7910 - accuracy: 0.8504 - val_loss: 0.6890 - val_accuracy: 0.9333
Epoch 84/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7881 - accuracy: 0.8504 - val_loss: 0.6864 - val_accuracy: 0.9333
Epoch 85/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7852 - accuracy: 0.8504 - val_loss: 0.6837 - val_accuracy: 0.9333
Epoch 86/100
4/4 [==============================] - 0s 11ms/step - loss: 0.7823 - accuracy: 0.8504 - val_loss: 0.6811 - val_accuracy: 0.9333
Epoch 87/100
4/4 [==============================] - 0s 12ms/step - loss: 0.7796 - accuracy: 0.8504 - val_loss: 0.6786 - val_accuracy: 0.9333
Epoch 88/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7767 - accuracy: 0.8425 - val_loss: 0.6761 - val_accuracy: 1.0000
Epoch 89/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7738 - accuracy: 0.8504 - val_loss: 0.6734 - val_accuracy: 1.0000
Epoch 90/100
4/4 [==============================] - 0s 12ms/step - loss: 0.7710 - accuracy: 0.8504 - val_loss: 0.6707 - val_accuracy: 1.0000
Epoch 91/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7682 - accuracy: 0.8504 - val_loss: 0.6680 - val_accuracy: 1.0000
Epoch 92/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7656 - accuracy: 0.8504 - val_loss: 0.6651 - val_accuracy: 1.0000
Epoch 93/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7627 - accuracy: 0.8504 - val_loss: 0.6628 - val_accuracy: 1.0000
Epoch 94/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7599 - accuracy: 0.8583 - val_loss: 0.6603 - val_accuracy: 1.0000
Epoch 95/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7573 - accuracy: 0.8661 - val_loss: 0.6578 - val_accuracy: 1.0000
Epoch 96/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7545 - accuracy: 0.8661 - val_loss: 0.6553 - val_accuracy: 1.0000
Epoch 97/100
4/4 [==============================] - 0s 10ms/step - loss: 0.7518 - accuracy: 0.8661 - val_loss: 0.6528 - val_accuracy: 1.0000
Epoch 98/100
4/4 [==============================] - 0s 11ms/step - loss: 0.7492 - accuracy: 0.8661 - val_loss: 0.6503 - val_accuracy: 1.0000
Epoch 99/100
4/4 [==============================] - 0s 9ms/step - loss: 0.7465 - accuracy: 0.8661 - val_loss: 0.6479 - val_accuracy: 1.0000
Epoch 100/100
4/4 [==============================] - 0s 16ms/step - loss: 0.7438 - accuracy: 0.8661 - val_loss: 0.6454 - val_accuracy: 1.0000

In [105]:
performance_test = model.evaluate(x_test, y_test)

print('Test Loss : {:.6f},  Test Accuracy : {:.3f}%'.format(performance_test[0], performance_test[1]*100))

2/2 [==============================] - 0s 4ms/step - loss: 462.5774 - accuracy: 0.3056
Test Loss : 462.577362,  Test Accuracy : 30.556%